jre:
  linked: false
lucy_server_portal:
  charset: de_DE.UTF-8
packages:
  database_drivers: true
  installer: true
  jre: true
  lucy_manager_portal: true
  lucy_server_portal: true
  lucy_server_portal_standalone: true
  solr: true
setup:
  installationDir: /opt/intrexx
  instance:
    createDaemonUser: true
    daemonManager: SYSTEMD
    daemonUser: intrexx
    serviceStartType: AUTO_START
  javaHomeDir: /setup/tmp/intrexx-setup/java/packaged/linux/amd64
  javaProvided: true
  sourceDir: /setup/tmp/intrexx-setup
solr:
  cloudMode: false
  host: 127.0.0.1
  password: ixape-v1:7FCB1FA944264EA964C89B6E0FADC0627C9683ABBF6435983C
  port: 8983
  user: solr
